name: Build

concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: src

      - name: Create builds directory
        run: mkdir -p $GITHUB_WORKSPACE/builds

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds || echo "No .cs3 found"
          cp build/plugins.json $GITHUB_WORKSPACE/builds || echo "No plugins.json found"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xalaflix-extensions
          path: builds/
